### ISSUE TITLE
O código está pouco legível e o site contém ambiguidades

### ISSUE THREAD

**Issue by lucascesar918** [julianamoon/find-the-number#1]
Daqui a pouco vou mandar um pull request, mas basicamente os textos de "your number" na index são ambíguos. Quais números são os "seus números", o aleatório, o primeiro digitado ou o segundo digitado? Além disso o código não tem variáveis bem descritivas, coloque nomes que qualquer um consiga saber facilmente do que a mesma se trata.

**Comment by julianamoon** [comment]
obrigada pelo feedback e a ajuda!
